### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by Nova001Sol** [sky0-1/Nomadic-Tents-1.9#1]
So I made a large yurt, build it up and entered. Thing is, the dimension took well over an hour to generate, so I killed MC. Now I can't access the world anymore. It crashes upon load, giving me this log. http://pastebin.com/HZ9ZGhRg

**Comment by GSValore** [comment]
I tried to trace the error for this as I was getting it also.  I turns out that because TentChunkProvider inherits both IChunkGenerator and IChunkProvider it has an ambiguity regarding provideChunk(int, int).  When you reobf the jar, it results in it picking only one of them and thus an AbstractMethodError since the other no longer exists.

Suggestion: Decouple the class and create a separate provider and generator to avoid this ambiguity.

Evidence to support the statements above:
Crash error log is looking for func_185932_a(II)Lnet/minecraft/world/chunk/Chunk
Decompilation of the distribution jar shows func_186025_d(II)Lnet/minecraft/world/chunk/Chunk

The methods.csv denotes both of these are called provideChunk; IChunkGenerator and IChunkProvider have this method in their design.

**Comment by sky0-1** [comment]
Thanks for that advice. The issue is now resolved. I didn't realize that both of those interfaces had the same function, and it makes sense that it would cause problems.
