### ISSUE TITLE
The game does not start.

### ISSUE THREAD

**Issue by grodax** [sky0-1/Nomadic-Tents-1.9#3]
http://pastebin.com/tBTNsECd

**Comment by sky0-1** [comment]
Check your mods folder and make sure you only have one version of Nomadic Tents ( **NomadicTents[1.7.10]-1.08.jar** ). The crashlog says you also have **NomadicTents[1.7.10]-1.06.jar** which you need to remove

**Comment by grodax** [comment]
nothing changed.
![bandicam 2016-05-16 17-08-09-735](https://cloud.githubusercontent.com/assets/13678733/15291962/64c46396-1b89-11e6-9942-c00b1595e421.jpg)

**Comment by grodax** [comment]
error the same.

**Comment by GSValore** [comment]
I looked into this out of curiosity, it turns out the 1.7.10 (did not check other ones) contain duplicates of the primary class.  This was hinted by grodax's error log:

        yurtmod{1.08} [Nomadic Tents] (NomadicTents[1.7.10]-1.08.jar)
        yurtmod{1.06} [Nomadic Tents] (NomadicTents[1.7.10]-1.08.jar) 

It showed the same jar; you will find com/yurtmod/main/YurtMain.class & com/yurtmod/main/NomadicTents.class are both versions of the mod.  In theory, just deleting the YurtMain.class which is for 1.06 should fix the bug.

**Comment by grodax** [comment]
It turned out it works, but when you try to put up a tent crashes game.
http://pastebin.com/h52aigMP

**Comment by GSValore** [comment]
Unfortunately, I have no suggestion on how to fix that (without code changes); it seems it's not able to get some NBT data if I'm reading the code right (due to obfuscation) and throwing an error as a result.

**Comment by sky0-1** [comment]
Ah, I see now. I'll re-export the mod -- I was not aware that YurtMain was still there the first time

**Comment by sky0-1** [comment]
I have fixed these issues in Nomadic Tents 1.10
